package com.timeseries.util;

public class Queries {

	public static final String CREATE_INSTRUMENT_PRICE_MODIFIER = "CREATE TABLE INSTRUMENT_PRICE_MODIFIER (ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),NAME VARCHAR(50),MULTIPLIER DOUBLE)";
	public static final String INSERT_INSTRUMENT_PRICE_MODIFIER = "INSERT INTO INSTRUMENT_PRICE_MODIFIER(NAME,MULTIPLIER) VALUES(?,?)";
	public static final String DROP_INSTRUMENT_PRICE_MODIFIER = "DROP TABLE INSTRUMENT_PRICE_MODIFIER";
	public static final String GET_MODIFIER_FOR_INSTRUMENT = "SELECT MULTIPLIER FROM INSTRUMENT_PRICE_MODIFIER WHERE NAME=?";
}
